// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKbtkPFeocpx28E_qxXU2MGjYWsDYClWo',
    appId: '1:309799891308:web:7a69e3da9f2ec0ba070349',
    messagingSenderId: '309799891308',
    projectId: 'pink-store-3c649',
    authDomain: 'pink-store-3c649.firebaseapp.com',
    storageBucket: 'pink-store-3c649.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw4n3gC2sC4mO4RheedFUgZ7upiLIyyDg',
    appId: '1:309799891308:android:39ae153721f3ba8a070349',
    messagingSenderId: '309799891308',
    projectId: 'pink-store-3c649',
    storageBucket: 'pink-store-3c649.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIPiH9twnx0m_vQDcHTOtSWqGw9UofTjU',
    appId: '1:309799891308:ios:014980b0ba4aedc6070349',
    messagingSenderId: '309799891308',
    projectId: 'pink-store-3c649',
    storageBucket: 'pink-store-3c649.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIPiH9twnx0m_vQDcHTOtSWqGw9UofTjU',
    appId: '1:309799891308:ios:014980b0ba4aedc6070349',
    messagingSenderId: '309799891308',
    projectId: 'pink-store-3c649',
    storageBucket: 'pink-store-3c649.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKbtkPFeocpx28E_qxXU2MGjYWsDYClWo',
    appId: '1:309799891308:web:4039bd7bddb8994b070349',
    messagingSenderId: '309799891308',
    projectId: 'pink-store-3c649',
    authDomain: 'pink-store-3c649.firebaseapp.com',
    storageBucket: 'pink-store-3c649.appspot.com',
  );
}
